name: dash_craft
description: Just playing around.
version: 1.0.0+1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  args: ^2.3.1
  logging: ^1.2.0
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.8
  very_good_analysis: ^5.1.0